package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class App extends Exp {
  public final String ident_;
  public final ListExp listexp_;

  public App(String p1, ListExp p2) { ident_ = p1; listexp_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.App) {
      com.biosimilarity.lift.model.vorpal.Absyn.App x = (com.biosimilarity.lift.model.vorpal.Absyn.App)o;
      return this.ident_.equals(x.ident_) && this.listexp_.equals(x.listexp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listexp_.hashCode();
  }


}
