package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Arg {
  public final String ident_;

  public Arg(String p1) { ident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Arg) {
      com.biosimilarity.lift.model.vorpal.Absyn.Arg x = (com.biosimilarity.lift.model.vorpal.Absyn.Arg)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.Arg p, A arg);

  }

}
