package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class Cat implements java.io.Serializable {
  public abstract <R,A> R accept(Cat.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.ListCat p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.IdCat p, A arg);

  }

}
