package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Coercions extends Def {
  public final String ident_;
  public final Integer integer_;

  public Coercions(String p1, Integer p2) { ident_ = p1; integer_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Coercions) {
      com.biosimilarity.lift.model.vorpal.Absyn.Coercions x = (com.biosimilarity.lift.model.vorpal.Absyn.Coercions)o;
      return this.ident_.equals(x.ident_) && this.integer_.equals(x.integer_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.integer_.hashCode();
  }


}
