package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Comments extends Def {
  public final String string_1, string_2;

  public Comments(String p1, String p2) { string_1 = p1; string_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Comments) {
      com.biosimilarity.lift.model.vorpal.Absyn.Comments x = (com.biosimilarity.lift.model.vorpal.Absyn.Comments)o;
      return this.string_1.equals(x.string_1) && this.string_2.equals(x.string_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.string_1.hashCode())+this.string_2.hashCode();
  }


}
