package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Comment extends Def {
  public final String string_;

  public Comment(String p1) { string_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Comment) {
      com.biosimilarity.lift.model.vorpal.Absyn.Comment x = (com.biosimilarity.lift.model.vorpal.Absyn.Comment)o;
      return this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return this.string_.hashCode();
  }


}
