package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Continuation extends Expression {
  public final ContinueExpr continueexpr_;

  public Continuation(ContinueExpr p1) { continueexpr_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Expression.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Continuation) {
      com.biosimilarity.lift.model.vorpal.Absyn.Continuation x = (com.biosimilarity.lift.model.vorpal.Absyn.Continuation)o;
      return this.continueexpr_.equals(x.continueexpr_);
    }
    return false;
  }

  public int hashCode() {
    return this.continueexpr_.hashCode();
  }


}
