package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class DefSome extends LDef {
  public final ListIdent listident_;
  public final Def def_;

  public DefSome(ListIdent p1, Def p2) { listident_ = p1; def_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.LDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.DefSome) {
      com.biosimilarity.lift.model.vorpal.Absyn.DefSome x = (com.biosimilarity.lift.model.vorpal.Absyn.DefSome)o;
      return this.listident_.equals(x.listident_) && this.def_.equals(x.def_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.listident_.hashCode())+this.def_.hashCode();
  }


}
