package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Function extends Def {
  public final String ident_;
  public final ListArg listarg_;
  public final Exp exp_;

  public Function(String p1, ListArg p2, Exp p3) { ident_ = p1; listarg_ = p2; exp_ = p3; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Function) {
      com.biosimilarity.lift.model.vorpal.Absyn.Function x = (com.biosimilarity.lift.model.vorpal.Absyn.Function)o;
      return this.ident_.equals(x.ident_) && this.listarg_.equals(x.listarg_) && this.exp_.equals(x.exp_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.ident_.hashCode())+this.listarg_.hashCode())+this.exp_.hashCode();
  }


}
