package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Grammar {
  public final ListDef listdef_;

  public Grammar(ListDef p1) { listdef_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Grammar.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Grammar) {
      com.biosimilarity.lift.model.vorpal.Absyn.Grammar x = (com.biosimilarity.lift.model.vorpal.Absyn.Grammar)o;
      return this.listdef_.equals(x.listdef_);
    }
    return false;
  }

  public int hashCode() {
    return this.listdef_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.Grammar p, A arg);

  }

}
