package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Id extends LabelId {
  public final String ident_;

  public Id(String p1) { ident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.LabelId.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Id) {
      com.biosimilarity.lift.model.vorpal.Absyn.Id x = (com.biosimilarity.lift.model.vorpal.Absyn.Id)o;
      return this.ident_.equals(x.ident_);
    }
    return false;
  }

  public int hashCode() {
    return this.ident_.hashCode();
  }


}
