package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Ints extends IntList {
  public final ListInteger listinteger_;

  public Ints(ListInteger p1) { listinteger_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.IntList.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Ints) {
      com.biosimilarity.lift.model.vorpal.Absyn.Ints x = (com.biosimilarity.lift.model.vorpal.Absyn.Ints)o;
      return this.listinteger_.equals(x.listinteger_);
    }
    return false;
  }

  public int hashCode() {
    return this.listinteger_.hashCode();
  }


}
