package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class LabelId implements java.io.Serializable {
  public abstract <R,A> R accept(LabelId.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.Id p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.Wild p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.ListE p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.ListCons p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.ListOne p, A arg);

  }

}
