package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class Label implements java.io.Serializable {
  public abstract <R,A> R accept(Label.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.LabNoP p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.LabP p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.LabPF p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.LabF p, A arg);

  }

}
