package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class LabNoP extends Label {
  public final LabelId labelid_;

  public LabNoP(LabelId p1) { labelid_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Label.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.LabNoP) {
      com.biosimilarity.lift.model.vorpal.Absyn.LabNoP x = (com.biosimilarity.lift.model.vorpal.Absyn.LabNoP)o;
      return this.labelid_.equals(x.labelid_);
    }
    return false;
  }

  public int hashCode() {
    return this.labelid_.hashCode();
  }


}
