package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class LayoutStop extends Def {
  public final ListString liststring_;

  public LayoutStop(ListString p1) { liststring_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.LayoutStop) {
      com.biosimilarity.lift.model.vorpal.Absyn.LayoutStop x = (com.biosimilarity.lift.model.vorpal.Absyn.LayoutStop)o;
      return this.liststring_.equals(x.liststring_);
    }
    return false;
  }

  public int hashCode() {
    return this.liststring_.hashCode();
  }


}
