package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class LDefView extends LDef {
  public final ListIdent listident_;

  public LDefView(ListIdent p1) { listident_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.LDef.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.LDefView) {
      com.biosimilarity.lift.model.vorpal.Absyn.LDefView x = (com.biosimilarity.lift.model.vorpal.Absyn.LDefView)o;
      return this.listident_.equals(x.listident_);
    }
    return false;
  }

  public int hashCode() {
    return this.listident_.hashCode();
  }


}
