package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class LGrammar implements java.io.Serializable {
  public abstract <R,A> R accept(LGrammar.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.LGr p, A arg);

  }

}
