package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class LitChar extends Exp {
  public final Character char_;

  public LitChar(Character p1) { char_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.LitChar) {
      com.biosimilarity.lift.model.vorpal.Absyn.LitChar x = (com.biosimilarity.lift.model.vorpal.Absyn.LitChar)o;
      return this.char_.equals(x.char_);
    }
    return false;
  }

  public int hashCode() {
    return this.char_.hashCode();
  }


}
