package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class MinimumSize implements java.io.Serializable {
  public abstract <R,A> R accept(MinimumSize.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.MNonempty p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.MEmpty p, A arg);

  }

}
