package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class NTerminal extends Item {
  public final Cat cat_;

  public NTerminal(Cat p1) { cat_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Item.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.NTerminal) {
      com.biosimilarity.lift.model.vorpal.Absyn.NTerminal x = (com.biosimilarity.lift.model.vorpal.Absyn.NTerminal)o;
      return this.cat_.equals(x.cat_);
    }
    return false;
  }

  public int hashCode() {
    return this.cat_.hashCode();
  }


}
