package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public abstract class Reg implements java.io.Serializable {
  public abstract <R,A> R accept(Reg.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RSeq p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RAlt p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RMinus p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RStar p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RPlus p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.ROpt p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.REps p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RChar p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RAlts p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RSeqs p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RDigit p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RLetter p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RUpper p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RLower p, A arg);
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RAny p, A arg);

  }

}
