package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class RHS {
  public final ListItem listitem_;

  public RHS(ListItem p1) { listitem_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.RHS.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.RHS) {
      com.biosimilarity.lift.model.vorpal.Absyn.RHS x = (com.biosimilarity.lift.model.vorpal.Absyn.RHS)o;
      return this.listitem_.equals(x.listitem_);
    }
    return false;
  }

  public int hashCode() {
    return this.listitem_.hashCode();
  }

  public interface Visitor <R,A> {
    public R visit(com.biosimilarity.lift.model.vorpal.Absyn.RHS p, A arg);

  }

}
