package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class RLetter extends Reg {

  public RLetter() { }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Reg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.RLetter) {
      return true;
    }
    return false;
  }

  public int hashCode() {
    return 37;
  }


}
