package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class RMinus extends Reg {
  public final Reg reg_1, reg_2;

  public RMinus(Reg p1, Reg p2) { reg_1 = p1; reg_2 = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Reg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.RMinus) {
      com.biosimilarity.lift.model.vorpal.Absyn.RMinus x = (com.biosimilarity.lift.model.vorpal.Absyn.RMinus)o;
      return this.reg_1.equals(x.reg_1) && this.reg_2.equals(x.reg_2);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.reg_1.hashCode())+this.reg_2.hashCode();
  }


}
