package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class RStar extends Reg {
  public final Reg reg_;

  public RStar(Reg p1) { reg_ = p1; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Reg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.RStar) {
      com.biosimilarity.lift.model.vorpal.Absyn.RStar x = (com.biosimilarity.lift.model.vorpal.Absyn.RStar)o;
      return this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return this.reg_.hashCode();
  }


}
