package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Rules extends Def {
  public final String ident_;
  public final ListRHS listrhs_;

  public Rules(String p1, ListRHS p2) { ident_ = p1; listrhs_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Rules) {
      com.biosimilarity.lift.model.vorpal.Absyn.Rules x = (com.biosimilarity.lift.model.vorpal.Absyn.Rules)o;
      return this.ident_.equals(x.ident_) && this.listrhs_.equals(x.listrhs_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.listrhs_.hashCode();
  }


}
