package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Rule extends Def {
  public final Label label_;
  public final Cat cat_;
  public final ListItem listitem_;

  public Rule(Label p1, Cat p2, ListItem p3) { label_ = p1; cat_ = p2; listitem_ = p3; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Rule) {
      com.biosimilarity.lift.model.vorpal.Absyn.Rule x = (com.biosimilarity.lift.model.vorpal.Absyn.Rule)o;
      return this.label_.equals(x.label_) && this.cat_.equals(x.cat_) && this.listitem_.equals(x.listitem_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.label_.hashCode())+this.cat_.hashCode())+this.listitem_.hashCode();
  }


}
