package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Terminator extends Def {
  public final MinimumSize minimumsize_;
  public final Cat cat_;
  public final String string_;

  public Terminator(MinimumSize p1, Cat p2, String p3) { minimumsize_ = p1; cat_ = p2; string_ = p3; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Terminator) {
      com.biosimilarity.lift.model.vorpal.Absyn.Terminator x = (com.biosimilarity.lift.model.vorpal.Absyn.Terminator)o;
      return this.minimumsize_.equals(x.minimumsize_) && this.cat_.equals(x.cat_) && this.string_.equals(x.string_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.minimumsize_.hashCode())+this.cat_.hashCode())+this.string_.hashCode();
  }


}
