package com.biosimilarity.lift.model.vorpal.Absyn; // Java Package generated by the BNF Converter.

public class Token extends Def {
  public final String ident_;
  public final Reg reg_;

  public Token(String p1, Reg p2) { ident_ = p1; reg_ = p2; }

  public <R,A> R accept(com.biosimilarity.lift.model.vorpal.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof com.biosimilarity.lift.model.vorpal.Absyn.Token) {
      com.biosimilarity.lift.model.vorpal.Absyn.Token x = (com.biosimilarity.lift.model.vorpal.Absyn.Token)o;
      return this.ident_.equals(x.ident_) && this.reg_.equals(x.reg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.ident_.hashCode())+this.reg_.hashCode();
  }


}
